import { library } from '@fortawesome/fontawesome-svg-core'
import {
    faCircleInfo,
    faCheck,
    faPenToSquare,
    faTrash,
    faPlus,
    faMinus,
    faXmark,
    faPen,
    faX,
    faPeopleGroup,
    faPeopleRobbery,
    faBoxesStacked,
    faBox,
    faQrcode,
    faCaretLeft,
    faFloppyDisk,
    faToggleOn,
    faToggleOff,
    faUserGear,
    faRightFromBracket,
    faUser
} from '@fortawesome/free-solid-svg-icons'

library.add(
    faCircleInfo,
    faCheck,
    faPenToSquare,
    faTrash,
    faPlus,
    faMinus,
    faXmark,
    faPen,
    faX,
    faPeopleGroup,
    faPeopleRobbery,
    faBoxesStacked,
    faBox,
    faQrcode,
    faCaretLeft,
    faFloppyDisk,
    faToggleOn,
    faToggleOff,
    faUserGear,
    faRightFromBracket,
    faUser
)
